version: '3'

services:
  api:
    container_name: api
    build: .
    restart: always
    ports:
      - 80:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000
  
  worker:
    container_name: worker
    build: .
    restart: always
    command: arq core.worker.WorkerSettings
  
  redis:
    image: redis:6-alpine
    restart: always
    container_name: redis
    expose:
      - 6379