version: '3'

services:
  api:
    container_name: api
    build: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: sleep 365d
    depends_on:
      - redis
  
  redis:
    image: redis:6-alpine
    restart: always
    container_name: redis
    expose:
      - 6379